Traceback (most recent call last):
  File "c:\users\sk250164\desktop\mercury\jup\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\sk250164\desktop\mercury\jup\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\sk250164\desktop\mercury\jup\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\sk250164\desktop\mercury\jup\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\sk250164\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\users\sk250164\desktop\mercury\jup\lib\site-packages\nbclient\client.py", line 664, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\sk250164\desktop\mercury\jup\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\sk250164\desktop\mercury\jup\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import os
import sys
import re
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import TextConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
from io import BytesIO


def clear_text():
   open("Output.txt", "w").close()
   
#writelines function
def writelines(self, lines):
    self._checkClosed()
    for line in lines:
       self.write(line)

#PDF to text Function. 
def pdf_to_text(path):
    manager = PDFResourceManager()
    retstr = BytesIO()
    layout = LAParams(all_texts=True)
    device = TextConverter(manager, retstr, laparams=layout)
    filepath = open(path, 'rb')
    interpreter = PDFPageInterpreter(manager, device)

    for page in PDFPage.get_pages(filepath, check_extractable=True):
        
        interpreter.process_page(page)

    text = retstr.getvalue()
    filepath.close()
    device.close()
    retstr.close()
    return text

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_24944\1867440359.py[0m in [0;36m<module>[1;34m[0m
[0;32m      2[0m [1;32mimport[0m [0msys[0m[1;33m[0m[1;33m[0m[0m
[0;32m      3[0m [1;32mimport[0m [0mre[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 4[1;33m [1;32mfrom[0m [0mpdfminer[0m[1;33m.[0m[0mpdfinterp[0m [1;32mimport[0m [0mPDFResourceManager[0m[1;33m,[0m [0mPDFPageInterpreter[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      5[0m [1;32mfrom[0m [0mpdfminer[0m[1;33m.[0m[0mconverter[0m [1;32mimport[0m [0mTextConverter[0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [1;32mfrom[0m [0mpdfminer[0m[1;33m.[0m[0mlayout[0m [1;32mimport[0m [0mLAParams[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'pdfminer'
ModuleNotFoundError: No module named 'pdfminer'

